name: Release

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Release Stage
        options:
        - alpha
        - beta
        - rc
        - gold
      version:
        default: "3.Y.Z"
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis in release notes

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: pip install isort black ruff
      - name: ISORT
        run: python -m isort . --check-only --diff
      - name: BLACK
        run: python -m black . --check --diff
      - name: Server set to production
        run: python3 -c 'from global_vars import SERVER; assert SERVER == "https://www.blenderkit.com"'
      - name: Version in daemon.py same as in __init__.py
        run: python3 -c 'from daemon.daemon import VERSION; from __init__ import bl_info; assert bl_info["version"] == tuple(map(int, VERSION.split(".")))'

  Release_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Version set to ${{inputs.version}}
        run: python3 -c 'from __init__ import bl_info; assert bl_info["version"] == tuple(map(int, "${{inputs.version}}.${{steps.date.outputs.date}}".split(".")))'

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build add-on
        run: python dev.py build
      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Store the build
        uses: actions/upload-artifact@v3
        with:
          name: blenderkit-v${{inputs.version}}.${{steps.date.outputs.date}}
          path: |
            out
            !out/blenderkit.zip

  make-tests-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: python .github/make-tests-matrix.py >> $GITHUB_OUTPUT

  TESTS:
    needs: make-tests-matrix
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.make-tests-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache Blender
        id: blenderBinaryCache
        uses: actions/cache@v3
        with:
          path: /home/runner/blender
          key: blender-${{matrix.version}}-${{matrix.sha}}
      - name: Download Blender
        if: steps.blenderBinaryCache.outputs.cache-hit != 'true'
        run: curl ${{ matrix.download_url }} -o /home/runner/blender.tar.xz
      - name: Mkdir
        run: mkdir {/home/runner/.local/bin,/home/runner/blender} -p
      - name: Extract Blender
        if: steps.blenderBinaryCache.outputs.cache-hit != 'true'
        run: tar -xf /home/runner/blender.tar.xz -C /home/runner/blender --strip-components=1
      - name: Add Blender to PATH
        run: ln -s /home/runner/blender/blender /home/runner/.local/bin/blender
      - name: TEST
        run: python dev.py test --install-at /home/runner/.config/blender/${{matrix.version_x_y}}/scripts/addons
